version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rivalslfg
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d rivalslfg"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.4.1-alpine
    restart: always
    container_name: rivalslfg-redis
    ports:
      - '32001:6379'
    environment:
      - REDIS_USERNAME=default
      - REDIS_PASSWORD=password
    command: redis-server --save 20 1 --loglevel warning --requirepass password

volumes:
  postgres_data:
