// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package repository

import (
	"context"
)

const findAllPlayers = `-- name: FindAllPlayers :many
SELECT id, name, display_name, region, platform, gamemode, roles, rank, characters, p_voice_chat, p_mic, vanguards, duelists, strategists, platforms, g_voice_chat, g_mic, created_at, updated_at FROM Players
`

func (q *Queries) FindAllPlayers(ctx context.Context) ([]Player, error) {
	rows, err := q.db.Query(ctx, findAllPlayers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Player
	for rows.Next() {
		var i Player
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DisplayName,
			&i.Region,
			&i.Platform,
			&i.Gamemode,
			&i.Roles,
			&i.Rank,
			&i.Characters,
			&i.PVoiceChat,
			&i.PMic,
			&i.Vanguards,
			&i.Duelists,
			&i.Strategists,
			&i.Platforms,
			&i.GVoiceChat,
			&i.GMic,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
